### PR TITLE
Add WDL implementation of the workflow

### PR DESCRIPTION
**Pull request by huddlej**
## Description of proposed changes

Adds a minimal WDL implementation of the workflow by porting the Snakefle to WDL syntax. Includes an inputs JSON file to parameterize the workflow akin to Snakemake's `--configfile` option. See the README for details on how to run the workflow with Cromwell.

## Testing

Install Java 11 and Auspice.

```
mamba create -n java -c conda-forge -c bioconda openjdk=11 auspice=2.29.1
conda activate java
```

[Download Cromwell and WOMtool binaries](https://github.com/broadinstitute/cromwell/releases).

```
mkdir -p bin
cd bin
curl -OL https://github.com/broadinstitute/cromwell/releases/download/69/cromwell-69.jar
curl -OL https://github.com/broadinstitute/cromwell/releases/download/69/womtool-69.jar
cd ..
```

Start Docker. Run the workflow.

```
java -jar bin/cromwell-69.jar run wdl/zika-tutorial.wdl -i wdl/inputs.json
```

View the resulting Auspice JSON in the execution directory of the Cromwell workflow (replacing `<workflow-id>` with the id for your run).

```
auspice view --datasetDir cromwell-executions/ZikaTutorial/<workflow-id>/call-Export/execution/
```

## Open questions

* How do I get a workflow to write output files to my current working directory? Do I always have to dig into a randomly named subdirectory of the Cromwell executions directory to find my outputs? This would be annoying.
* How do I control parallelization of the workflow? For example, how do I ensure I run my commands with a fixed number of cores and that the workflow will enforce those constraints? How does this all relate to “[hog factors](https://cromwell.readthedocs.io/en/stable/cromwell_features/HogFactors/)”?
* How do I perform a “dryrun” of the workflow without running the whole workflow?
* How do I see a list of commands that will be run (as in `snakemake -p`)?
* How do I enable [call caching](https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/) so I don’t have to run everything from scratch when the outputs exist already?
* Is it a good idea to make the Docker image string a top-level configuration variable of the workflow?
* Do we prefer syntax like `${variable}` or `~{variable}`? Both seem supported, but the latter seems preferred?
* How do I quote inputs to avoid shell interpretation errors?
* How do I run my jobs on [AWS Batch](https://cromwell.readthedocs.io/en/develop/tutorials/AwsBatch101/)? How do I run my jobs on [a SLURM backend](https://cromwell.readthedocs.io/en/develop/backends/SLURM/) like [the Hutch’s SLURM cluster](https://sciwiki.fredhutch.org/compdemos/Cromwell/)?

### CODE REVIEW

**Comment by tsibley** [comment]
I haven't given this a good look yet, but I wanted to jot down some early notes.

- There is a Conda package for Cromwell, so the install process can be greatly simplified.

    ```
    mamba create -n wdl -c conda-forge -c bioconda cromwell auspice=2.29.1
    conda activate wdl
    ```
    and then running is also simpler:
    
    ```
    cromwell run wdl/zika-tutorial.wdl -i wdl/inputs.json
    ```

- Several of your open questions have answers that involve [configuring Cromwell's options](https://cromwell.readthedocs.io/en/stable/Configuring/) to our preferences.

- Using `miniwdl` instead of Cromwell may be more appropriate. It has some defaults better suited to individual/personal usage rather than production/enterprise usage. For example, it produces symlinked run directories and outputs, so you can stably refer to workflow outputs like `wdl/runs/_LAST/out/auspice_json/zika.json` (when run as `miniwdl run -d wdl/runs/ …` for example). OTOH, Cromwell is more "standard" and maybe we can provide an options file configuring it for defaults like miniwdl.

**Comment by j23414** [comment]
Sorry for the premature merge (I added a revert to undo it).

@tsibley @huddlej Did we want to keep the "wdl" branch separate from the "master" (should be changed to "main") branch?

**Comment by tsibley** [comment]
@j23414 No worries. I think we were holding off merging the branch because of the many open questions and expected changes to be made still. i.e. it's generally nice not to have unfinished work in `master`. Long term, the plan is certainly to merge it though.

**Comment by j23414** [comment]
Regarding the question:

> How do I get a workflow to write output files to my current working directory? Do I always have to dig into a randomly named subdirectory of the Cromwell executions directory to find my outputs? This would be annoying.

Create an `options.json` file:

```
{
  "default_runtime_attributes": {
    "docker": "ubuntu:latest",
  },
  
  "final_workflow_outputs_dir" : "results",                   #<====== This one
  "use_relative_output_paths" : true,
  "final_workflow_log_dir" : "results/wf_logs",
  "final_call_logs_dir" : "results/call_logs"
}
```

And pass it to cromwell

```
cromwell run workflowscript.wdl -i inputs.json -o options.json
```

Although I'm still struggling to get `options.json` passed to dockstore (for Terra).

**Pull request merged**
